language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_deploy: yarn build
deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master